/joy_teleop:
  ros__parameters:
   # Default mode - Stop for safety
   default:
    type: topic
    is_default: true
    interface_type: ackermann_msgs/msg/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input/teleop
    deadman_buttons: []
    message_value:
      drive-speed:
        value: 0.0
      
      drive.steering_angle:
        value: 0.0

   # Enable Human control by holding Left Bumper
   human_control:
    type: topic
    interface_type: ackermann_msgs/msg/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input/teleop
    deadman_buttons: [4]
    axis_mappings:
      drive-speed:
        axis: 1
        scale: 2.0                   # joystick will command plus or minus 2 meters / second
        offset: 0.0
      drive-steering_angle:
        axis: 3
        scale: 0.34                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.0

   # Enable autonomous control by pressing right bumper
   # This switch causes the joy_teleop to stop sending messages to input/teleop
   # And send messages to /dev/null (an unused ROS topic)
   autonomous_control:
    type: topic
    interface_type: std_msgs/msg/Int8
    topic_name: /dev/null
    deadman_buttons: [5]
    message_value:
      data:
        value: 0 
